plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.0.2.cjs

packageExtensions:
  "@cryptopapers/admin@*":
    peerDependencies:
      "webpack": "*"
  "@cryptopapers/front@*":
    peerDependencies:
      "postcss": "*"
      "webpack": "*"
  "@cryptopapers/ui@*":
    peerDependencies:
      "webpack": "*"
  "@storybook/addon-info@5":
    dependencies:
      "regenerator-runtime": "*"
    peerDependencies:
      "react-dom": "*"
  "@storybook/api@5":
    peerDependencies:
      "react-dom": "*"
  "@storybook/core@6":
    peerDependencies:
      "@babel/core": "*"
      "webpack": "*"
  "@endemolshinegroup/cosmiconfig-typescript-loader@3":
    peerDependencies:
      "typescript": "*"
  "@mdx-js/loader@1":
    peerDependencies:
      "react": "*"
  "@storybook/addon-essentials@6":
    dependencies:
      "@storybook/components": "*"
      "@storybook/core-events": "*"
      "@storybook/theming": "*"
  "@storybook/addons@5":
    peerDependencies:
      "react-dom": "*"
      "regenerator-runtime": "*"
  "@storybook/core-server@6":
    peerDependencies:
      "@babel/core": "*"
  "@storybook/csf-tools@6":
    peerDependencies:
      "@babel/core": "*"
  "react-dev-utils@11":
    peerDependencies:
      "typescript": "*"
      "webpack": "*"
  "graphql-config@4":
    peerDependencies:
      "typescript": "*"
  "@graphql-codegen/cli@2":
    peerDependencies:
      "typescript": "*"

