// flow-typed signature: 1abfd9628347b516f77205e7cc15e512
// flow-typed version: <<STUB>>/next-compose_v0.0.2/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-compose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-compose' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'next-compose/index' {
  declare module.exports: $Exports<'next-compose'>;
}
declare module 'next-compose/index.js' {
  declare module.exports: $Exports<'next-compose'>;
}
