// flow-typed signature: 655b36f7162a272fcae6985f87a6f8c2
// flow-typed version: <<STUB>>/@zeit/next-mdx_v^1.2.0/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@zeit/next-mdx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@zeit/next-mdx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@zeit/next-mdx/index' {
  declare module.exports: $Exports<'@zeit/next-mdx'>;
}
declare module '@zeit/next-mdx/index.js' {
  declare module.exports: $Exports<'@zeit/next-mdx'>;
}
